### ISSUE TITLE
وبسایت بالا نمیاد جناب

### ISSUE THREAD

**Issue by shervinbdndev** [Sobhan-SRZA/Personal-Website#4]

**Comment by Sobhan-SRZA** [comment]
> وی پی ان بزن اوکی میشه

**Comment by shervinbdndev** [comment]
> > وی پی ان بزن اوکی میشه
> 

پیشنهاد میکنم از [https://vercel.com](vercel.com) استفاده کنید جناب

**Comment by Sobhan-SRZA** [comment]
> 
آیا هاست رایگان هست جناب؟ و اینکه خودش ظاهرا vpn  میخواد

**Comment by shervinbdndev** [comment]
> > 
> آیا هاست رایگان هست جناب؟ و اینکه خودش ظاهرا vpn  میخواد

آره رایگانه
با شاتل و تنهای اول هم بالا میاد
با ایرانسل گهگاهی اونم به زور

**Comment by Sobhan-SRZA** [comment]
> > > 
> > 
> > 
> > آیا هاست رایگان هست جناب؟ و اینکه خودش ظاهرا vpn  میخواد
> 
> آره رایگانه با شاتل و تنهای اول هم بالا میاد با ایرانسل گهگاهی اونم به زور

خیلی ممنون
